// This file is auto-generated by @hey-api/openapi-ts

export type ActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ActivityCreate = {
    type: ActivityType;
    subject: string;
    description?: (string | null);
    due_date?: (string | null);
    completed?: boolean;
    company_id: string;
    contact_id?: (string | null);
    deal_id?: (string | null);
};

export type ActivityPublic = {
    type: ActivityType;
    subject: string;
    description?: (string | null);
    due_date?: (string | null);
    completed?: boolean;
    id: string;
    company_id: string;
    contact_id: (string | null);
    deal_id: (string | null);
    owner_id: string;
    tenant_id: string;
    created_at?: (string | null);
};

export type ActivityType = 'call' | 'email' | 'meeting' | 'task';

export type ActivityUpdate = {
    type?: (ActivityType | null);
    subject?: (string | null);
    description?: (string | null);
    due_date?: (string | null);
    completed?: (boolean | null);
    company_id?: (string | null);
    contact_id?: (string | null);
    deal_id?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContactCreate = {
    first_name: string;
    last_name: string;
    title?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    linkedin_url?: (string | null);
    notes?: (string | null);
    company_id: string;
};

export type ContactPublic = {
    first_name: string;
    last_name: string;
    title?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    linkedin_url?: (string | null);
    notes?: (string | null);
    id: string;
    company_id: string;
    tenant_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ContactsPublic = {
    data: Array<ContactPublic>;
    count: number;
};

export type ContactUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    title?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    linkedin_url?: (string | null);
    notes?: (string | null);
    company_id?: (string | null);
};

export type CRMCompaniesPublic = {
    data: Array<CRMCompanyPublic>;
    count: number;
};

export type CRMCompanyCreate = {
    name: string;
    website?: (string | null);
    industry?: (string | null);
    employee_count?: (number | null);
    annual_revenue?: (number | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    country?: (string | null);
    notes?: (string | null);
};

export type CRMCompanyPublic = {
    name: string;
    website?: (string | null);
    industry?: (string | null);
    employee_count?: (number | null);
    annual_revenue?: (number | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    country?: (string | null);
    notes?: (string | null);
    id: string;
    tenant_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type CRMCompanyUpdate = {
    name?: (string | null);
    website?: (string | null);
    industry?: (string | null);
    employee_count?: (number | null);
    annual_revenue?: (number | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    country?: (string | null);
    notes?: (string | null);
};

export type DealCreate = {
    name: string;
    amount?: (number | null);
    stage?: DealStage;
    probability?: (number | null);
    expected_close_date?: (string | null);
    notes?: (string | null);
    company_id: string;
    contact_id?: (string | null);
};

export type DealPublic = {
    name: string;
    amount?: (number | null);
    stage?: DealStage;
    probability?: (number | null);
    expected_close_date?: (string | null);
    notes?: (string | null);
    id: string;
    company_id: string;
    contact_id: (string | null);
    owner_id: string;
    tenant_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type DealsPublic = {
    data: Array<DealPublic>;
    count: number;
};

export type DealStage = 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';

export type DealUpdate = {
    name?: (string | null);
    amount?: (number | null);
    stage?: (DealStage | null);
    probability?: (number | null);
    expected_close_date?: (string | null);
    notes?: (string | null);
    company_id?: (string | null);
    contact_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InviteMemberRequest = {
    user_id: string;
    role?: UserRole;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCreate = {
    content: string;
    company_id?: (string | null);
    contact_id?: (string | null);
    deal_id?: (string | null);
};

export type NotePublic = {
    content: string;
    id: string;
    company_id: (string | null);
    contact_id: (string | null);
    deal_id: (string | null);
    created_by: string;
    tenant_id: string;
    created_at?: (string | null);
};

export type NotesPublic = {
    data: Array<NotePublic>;
    count: number;
};

export type NoteUpdate = {
    content?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TenantCreate = {
    name: string;
    domain?: (string | null);
};

export type TenantMembershipPublic = {
    id: string;
    user_id: string;
    tenant_id: string;
    role: UserRole;
};

export type TenantPublic = {
    name: string;
    domain?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type TenantUpdate = {
    name?: (string | null);
    domain?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'admin' | 'manager' | 'sales_rep';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CrmActivitiesReadActivitiesData = {
    companyId?: (string | null);
    completed?: (boolean | null);
    contactId?: (string | null);
    dealId?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmActivitiesReadActivitiesResponse = (ActivitiesPublic);

export type CrmActivitiesCreateActivityData = {
    requestBody: ActivityCreate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmActivitiesCreateActivityResponse = (ActivityPublic);

export type CrmActivitiesReadActivityData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmActivitiesReadActivityResponse = (ActivityPublic);

export type CrmActivitiesUpdateActivityData = {
    id: string;
    requestBody: ActivityUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmActivitiesUpdateActivityResponse = (ActivityPublic);

export type CrmActivitiesDeleteActivityData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmActivitiesDeleteActivityResponse = (Message);

export type CrmCompaniesReadCompaniesData = {
    limit?: number;
    skip?: number;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmCompaniesReadCompaniesResponse = (CRMCompaniesPublic);

export type CrmCompaniesCreateCompanyData = {
    requestBody: CRMCompanyCreate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmCompaniesCreateCompanyResponse = (CRMCompanyPublic);

export type CrmCompaniesReadCompanyData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmCompaniesReadCompanyResponse = (CRMCompanyPublic);

export type CrmCompaniesUpdateCompanyData = {
    id: string;
    requestBody: CRMCompanyUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmCompaniesUpdateCompanyResponse = (CRMCompanyPublic);

export type CrmCompaniesDeleteCompanyData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmCompaniesDeleteCompanyResponse = (Message);

export type CrmContactsReadContactsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmContactsReadContactsResponse = (ContactsPublic);

export type CrmContactsCreateContactData = {
    requestBody: ContactCreate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmContactsCreateContactResponse = (ContactPublic);

export type CrmContactsReadContactData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmContactsReadContactResponse = (ContactPublic);

export type CrmContactsUpdateContactData = {
    id: string;
    requestBody: ContactUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmContactsUpdateContactResponse = (ContactPublic);

export type CrmContactsDeleteContactData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmContactsDeleteContactResponse = (Message);

export type CrmDealsReadDealsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
    stage?: (DealStage | null);
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmDealsReadDealsResponse = (DealsPublic);

export type CrmDealsCreateDealData = {
    requestBody: DealCreate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmDealsCreateDealResponse = (DealPublic);

export type CrmDealsReadDealData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmDealsReadDealResponse = (DealPublic);

export type CrmDealsUpdateDealData = {
    id: string;
    requestBody: DealUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmDealsUpdateDealResponse = (DealPublic);

export type CrmDealsDeleteDealData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmDealsDeleteDealResponse = (Message);

export type CrmNotesReadNotesData = {
    companyId?: (string | null);
    contactId?: (string | null);
    dealId?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmNotesReadNotesResponse = (NotesPublic);

export type CrmNotesCreateNoteData = {
    requestBody: NoteCreate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmNotesCreateNoteResponse = (NotePublic);

export type CrmNotesUpdateNoteData = {
    id: string;
    requestBody: NoteUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmNotesUpdateNoteResponse = (NotePublic);

export type CrmNotesDeleteNoteData = {
    id: string;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmNotesDeleteNoteResponse = (Message);

export type CrmTenantsCreateTenantData = {
    requestBody: TenantCreate;
};

export type CrmTenantsCreateTenantResponse = (TenantPublic);

export type CrmTenantsReadTenantData = {
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmTenantsReadTenantResponse = (TenantPublic);

export type CrmTenantsUpdateTenantData = {
    requestBody: TenantUpdate;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmTenantsUpdateTenantResponse = (TenantPublic);

export type CrmTenantsAddMemberData = {
    requestBody: InviteMemberRequest;
    /**
     * Tenant UUID
     */
    tenantId: string;
};

export type CrmTenantsAddMemberResponse = (TenantMembershipPublic);

export type CrmTenantsRemoveMemberData = {
    /**
     * Tenant UUID
     */
    tenantId: string;
    userId: string;
};

export type CrmTenantsRemoveMemberResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);