"""add notes text column to crm tables

Revision ID: 2ccba363a72f
Revises: 77fbd1799d64
Create Date: 2026-06-05 22:36:32.468280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ccba363a72f'
down_revision = '77fbd1799d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('crm_company', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('deal', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'notes')
    op.drop_column('crm_company', 'notes')
    op.drop_column('contact', 'notes')
    # ### end Alembic commands ###
