"""Add company table

Revision ID: 77fbd1799d64
Revises: 219cf5a0b1ee
Create Date: 2026-06-05 13:09:44.067190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77fbd1799d64'
down_revision = '219cf5a0b1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_company',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_company_tenant_id'), 'crm_company', ['tenant_id'], unique=False)
    op.create_table('tenant_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'sales_rep', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_company_id'), 'contact', ['company_id'], unique=False)
    op.create_index(op.f('ix_contact_tenant_id'), 'contact', ['tenant_id'], unique=False)
    op.create_table('deal',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage', sa.Enum('lead', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost', name='dealstage'), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_company_id'), 'deal', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_contact_id'), 'deal', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deal_owner_id'), 'deal', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deal_tenant_id'), 'deal', ['tenant_id'], unique=False)
    op.create_table('activity',
    sa.Column('type', sa.Enum('call', 'email', 'meeting', 'task', name='activitytype'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_company_id'), 'activity', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_owner_id'), 'activity', ['owner_id'], unique=False)
    op.create_index(op.f('ix_activity_tenant_id'), 'activity', ['tenant_id'], unique=False)
    op.create_table('note',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_company_id'), 'note', ['company_id'], unique=False)
    op.create_index(op.f('ix_note_contact_id'), 'note', ['contact_id'], unique=False)
    op.create_index(op.f('ix_note_created_by'), 'note', ['created_by'], unique=False)
    op.create_index(op.f('ix_note_deal_id'), 'note', ['deal_id'], unique=False)
    op.create_index(op.f('ix_note_tenant_id'), 'note', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_tenant_id'), table_name='note')
    op.drop_index(op.f('ix_note_deal_id'), table_name='note')
    op.drop_index(op.f('ix_note_created_by'), table_name='note')
    op.drop_index(op.f('ix_note_contact_id'), table_name='note')
    op.drop_index(op.f('ix_note_company_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_activity_tenant_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_owner_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_company_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_deal_tenant_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_owner_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_contact_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_company_id'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_contact_tenant_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_company_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_table('tenant_membership')
    op.drop_index(op.f('ix_crm_company_tenant_id'), table_name='crm_company')
    op.drop_table('crm_company')
    op.drop_table('tenant')
    # ### end Alembic commands ###
