/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCrmPipelineRouteImport } from './routes/_layout/crm/pipeline'
import { Route as LayoutCrmNotesRouteImport } from './routes/_layout/crm/notes'
import { Route as LayoutCrmDealsRouteImport } from './routes/_layout/crm/deals'
import { Route as LayoutCrmContactsRouteImport } from './routes/_layout/crm/contacts'
import { Route as LayoutCrmCompaniesRouteImport } from './routes/_layout/crm/companies'
import { Route as LayoutCrmActivitiesRouteImport } from './routes/_layout/crm/activities'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmPipelineRoute = LayoutCrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmNotesRoute = LayoutCrmNotesRouteImport.update({
  id: '/crm/notes',
  path: '/crm/notes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmDealsRoute = LayoutCrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmContactsRoute = LayoutCrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmCompaniesRoute = LayoutCrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrmActivitiesRoute = LayoutCrmActivitiesRouteImport.update({
  id: '/crm/activities',
  path: '/crm/activities',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/crm/activities': typeof LayoutCrmActivitiesRoute
  '/crm/companies': typeof LayoutCrmCompaniesRoute
  '/crm/contacts': typeof LayoutCrmContactsRoute
  '/crm/deals': typeof LayoutCrmDealsRoute
  '/crm/notes': typeof LayoutCrmNotesRoute
  '/crm/pipeline': typeof LayoutCrmPipelineRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/crm/activities': typeof LayoutCrmActivitiesRoute
  '/crm/companies': typeof LayoutCrmCompaniesRoute
  '/crm/contacts': typeof LayoutCrmContactsRoute
  '/crm/deals': typeof LayoutCrmDealsRoute
  '/crm/notes': typeof LayoutCrmNotesRoute
  '/crm/pipeline': typeof LayoutCrmPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/crm/activities': typeof LayoutCrmActivitiesRoute
  '/_layout/crm/companies': typeof LayoutCrmCompaniesRoute
  '/_layout/crm/contacts': typeof LayoutCrmContactsRoute
  '/_layout/crm/deals': typeof LayoutCrmDealsRoute
  '/_layout/crm/notes': typeof LayoutCrmNotesRoute
  '/_layout/crm/pipeline': typeof LayoutCrmPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/crm/activities'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/notes'
    | '/crm/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/crm/activities'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/notes'
    | '/crm/pipeline'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/crm/activities'
    | '/_layout/crm/companies'
    | '/_layout/crm/contacts'
    | '/_layout/crm/deals'
    | '/_layout/crm/notes'
    | '/_layout/crm/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/pipeline': {
      id: '/_layout/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof LayoutCrmPipelineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/notes': {
      id: '/_layout/crm/notes'
      path: '/crm/notes'
      fullPath: '/crm/notes'
      preLoaderRoute: typeof LayoutCrmNotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/deals': {
      id: '/_layout/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof LayoutCrmDealsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/contacts': {
      id: '/_layout/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof LayoutCrmContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/companies': {
      id: '/_layout/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof LayoutCrmCompaniesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crm/activities': {
      id: '/_layout/crm/activities'
      path: '/crm/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof LayoutCrmActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCrmActivitiesRoute: typeof LayoutCrmActivitiesRoute
  LayoutCrmCompaniesRoute: typeof LayoutCrmCompaniesRoute
  LayoutCrmContactsRoute: typeof LayoutCrmContactsRoute
  LayoutCrmDealsRoute: typeof LayoutCrmDealsRoute
  LayoutCrmNotesRoute: typeof LayoutCrmNotesRoute
  LayoutCrmPipelineRoute: typeof LayoutCrmPipelineRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCrmActivitiesRoute: LayoutCrmActivitiesRoute,
  LayoutCrmCompaniesRoute: LayoutCrmCompaniesRoute,
  LayoutCrmContactsRoute: LayoutCrmContactsRoute,
  LayoutCrmDealsRoute: LayoutCrmDealsRoute,
  LayoutCrmNotesRoute: LayoutCrmNotesRoute,
  LayoutCrmPipelineRoute: LayoutCrmPipelineRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
